# Generated by Django 2.1.1 on 2019-05-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thoughtspost',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='thoughtspost',
            name='body',
        ),
        migrations.RemoveField(
            model_name='thoughtspost',
            name='column',
        ),
        migrations.RemoveField(
            model_name='thoughtspost',
            name='tags',
        ),
    ]
