# Generated by Django 2.1.1 on 2019-05-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('nickname', models.CharField(blank=True, default='', max_length=45)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'nickname'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('last_name', 'first_name', 'nickname')},
        ),
    ]
